GET http://localhost:8080/api/bookings/Neukkari1
###
POST http://localhost:8080/api/bookings
Content-Type: application/json

{
  "roomName": "Neukkari1",
  "startTime": "2026-01-19T23:35:00",
  "endTime": "2026-01-20T00:15:00"
}
###
DELETE http://localhost:8080/api/bookings/<varauksen id>